<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
const api='/api', contracts=ref([]), settlements=ref([]), dashboard=ref(null), loading=ref(true), saving=ref(false), error=ref('')
const active=ref('dashboard'), query=ref(''), openGroups=reactive({contracts:true,settlements:true}), showForm=ref(false), formKind=ref('contract'), editingId=ref(null)
const contractBlank=()=>({type:'owner',number:'',name:'',counterparty:'',amount:0,settledAmount:0,paidAmount:0,signDate:'',startDate:'',endDate:'',status:'拟签订',manager:'',notes:''})
const settlementBlank=()=>({type:'owner',number:'',contractNumber:'',contractName:'',counterparty:'',period:'',reportedAmount:0,approvedAmount:0,paidAmount:0,status:'编制中',manager:'',notes:''})
const form=reactive(contractBlank()), contractStatuses=['拟签订','履约中','已完工','已结算','已终止'], settlementStatuses=['编制中','已申报','审核中','已审核','已支付','已关闭']
const isSettlement=computed(()=>active.value.startsWith('settlement-')), type=computed(()=>active.value.endsWith('subcontract')?'subcontract':'owner')
const pageTitle=computed(()=>({dashboard:'经营总览','contract-owner':'业主合同','contract-subcontract':'分包合同','settlement-owner':'业主结算','settlement-subcontract':'分包结算'})[active.value])
const currentItems=computed(()=>{const src=isSettlement.value?settlements.value:contracts.value;return src.filter(x=>x.type===type.value&&(!query.value||JSON.stringify(x).toLowerCase().includes(query.value.toLowerCase())))})
const fmt=v=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format(v||0)
async function load(){loading.value=true;error.value='';try{const rs=await Promise.all(['/contracts','/settlements','/dashboard'].map(p=>fetch(api+p)));if(rs.some(r=>!r.ok))throw new Error('数据加载失败');[contracts.value,settlements.value,dashboard.value]=await Promise.all(rs.map(r=>r.json()))}catch(e){error.value=e.message}finally{loading.value=false}}
function switchPage(key){active.value=key;query.value=''}
function openNew(){formKind.value=isSettlement.value?'settlement':'contract';Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,isSettlement.value?settlementBlank():contractBlank(),{type:type.value});editingId.value=null;showForm.value=true}
function edit(item,kind){formKind.value=kind;Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,item);editingId.value=item.id;showForm.value=true}
async function save(){saving.value=true;error.value='';try{const base=formKind.value==='settlement'?'settlements':'contracts',url=editingId.value?`${api}/${base}/${editingId.value}`:`${api}/${base}`;const res=await fetch(url,{method:editingId.value?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),data=await res.json();if(!res.ok)throw new Error(data?.error||'保存失败');showForm.value=false;await load()}catch(e){error.value=e.message}finally{saving.value=false}}
async function remove(item,kind){if(!confirm(`确认删除“${item.name||item.number}”吗？`))return;const res=await fetch(`${api}/${kind==='settlement'?'settlements':'contracts'}/${item.id}`,{method:'DELETE'});if(res.ok)await load();else error.value='删除失败'}
onMounted(load)
</script>
<template><div class="shell">
<aside><div class="brand"><span>商</span><div><strong>商务管理系统</strong><small>项目商务工作台</small></div></div><nav>
  <button class="top-item" :class="{active:active==='dashboard'}" @click="switchPage('dashboard')"><i></i>经营总览</button>
  <div class="nav-group"><button class="group-title" @click="openGroups.contracts=!openGroups.contracts"><span>合同管理</span><b>{{openGroups.contracts?'−':'+'}}</b></button><div v-show="openGroups.contracts" class="children"><button :class="{active:active==='contract-owner'}" @click="switchPage('contract-owner')">业主合同</button><button :class="{active:active==='contract-subcontract'}" @click="switchPage('contract-subcontract')">分包合同</button></div></div>
  <div class="nav-group"><button class="group-title" @click="openGroups.settlements=!openGroups.settlements"><span>结算管理</span><b>{{openGroups.settlements?'−':'+'}}</b></button><div v-show="openGroups.settlements" class="children"><button :class="{active:active==='settlement-owner'}" @click="switchPage('settlement-owner')">业主结算</button><button :class="{active:active==='settlement-subcontract'}" @click="switchPage('settlement-subcontract')">分包结算</button></div></div>
</nav><div class="aside-foot"><b>本地数据</b><p>合同与结算数据保存在当前电脑。</p></div></aside>
<main><header><div><small>项目商务管理</small><h1>{{pageTitle}}</h1></div><button v-if="active!=='dashboard'" class="primary" @click="openNew">＋ 新增{{isSettlement?'结算':'合同'}}</button></header><div v-if="error" class="alert">{{error}}<button @click="error=''">×</button></div>
<template v-if="active==='dashboard'"><section class="hero"><div><span>合同总额</span><strong>{{fmt((dashboard?.owner?.amount||0)+(dashboard?.subcontract?.amount||0))}}</strong><p>业主与分包合同统一归集</p></div><div class="rings"><div><b>{{contracts.length}}</b><small>合同总数</small></div></div></section><section class="cards"><article><div class="label owner">业主</div><span>业主合同额</span><strong>{{fmt(dashboard?.owner?.amount)}}</strong><footer>{{dashboard?.owner?.count||0}} 份合同 · 已收 {{fmt(dashboard?.owner?.paid)}}</footer></article><article><div class="label sub">分包</div><span>分包合同额</span><strong>{{fmt(dashboard?.subcontract?.amount)}}</strong><footer>{{dashboard?.subcontract?.count||0}} 份合同 · 已付 {{fmt(dashboard?.subcontract?.paid)}}</footer></article><article><span>结算记录</span><strong>{{settlements.length}} 笔</strong><footer>业主 {{settlements.filter(x=>x.type==='owner').length}} 笔 · 分包 {{settlements.filter(x=>x.type==='subcontract').length}} 笔</footer></article></section><section class="panel"><div class="panel-head"><div><h2>近期合同</h2><p>按最近更新时间排序</p></div></div><ContractTable :items="contracts.slice(0,5)" @edit="x=>edit(x,'contract')" @remove="x=>remove(x,'contract')" /></section></template>
<template v-else><section class="panel"><div class="toolbar"><div><h2>{{pageTitle}}台账</h2><p>共 {{currentItems.length}} 条记录</p></div><input v-model="query" :placeholder="isSettlement?'搜索结算编号、合同或相对方':'搜索编号、名称、相对方或经办人'" /></div><div v-if="loading" class="empty">正在加载数据…</div><SettlementTable v-else-if="isSettlement" :items="currentItems" @edit="x=>edit(x,'settlement')" @remove="x=>remove(x,'settlement')"/><ContractTable v-else :items="currentItems" @edit="x=>edit(x,'contract')" @remove="x=>remove(x,'contract')"/></section></template></main>
<div v-if="showForm" class="overlay" @click.self="showForm=false"><form class="drawer" @submit.prevent="save"><div class="drawer-head"><div><small>{{editingId?'编辑':'新建'}}{{formKind==='settlement'?'结算':'合同'}}</small><h2>{{formKind==='settlement'?'结算信息':'合同基本信息'}}</h2></div><button type="button" @click="showForm=false">×</button></div>
<div v-if="formKind==='contract'" class="form-grid"><label>合同类型<select v-model="form.type"><option value="owner">对业主</option><option value="subcontract">对分包</option></select></label><label>合同状态<select v-model="form.status"><option v-for="s in contractStatuses">{{s}}</option></select></label><label>合同编号<input v-model.trim="form.number" required /></label><label>合同名称<input v-model.trim="form.name" required /></label><label class="wide">合同相对方<input v-model.trim="form.counterparty" required /></label><label>合同金额<input v-model.number="form.amount" type="number" min="0" /></label><label>已结算金额<input v-model.number="form.settledAmount" type="number" min="0" /></label><label>已收/付款金额<input v-model.number="form.paidAmount" type="number" min="0" /></label><label>经办人<input v-model.trim="form.manager" /></label><label>签订日期<input v-model="form.signDate" type="date" /></label><label>开始日期<input v-model="form.startDate" type="date" /></label><label>结束日期<input v-model="form.endDate" type="date" /></label><label class="wide">备注<textarea v-model.trim="form.notes" rows="3"></textarea></label></div>
<div v-else class="form-grid"><label>结算类型<select v-model="form.type"><option value="owner">对业主</option><option value="subcontract">对分包</option></select></label><label>结算状态<select v-model="form.status"><option v-for="s in settlementStatuses">{{s}}</option></select></label><label>结算编号<input v-model.trim="form.number" required /></label><label>结算期间<input v-model="form.period" type="month" /></label><label>合同编号<input v-model.trim="form.contractNumber" /></label><label>合同名称<input v-model.trim="form.contractName" required /></label><label class="wide">结算相对方<input v-model.trim="form.counterparty" required /></label><label>申报金额<input v-model.number="form.reportedAmount" type="number" min="0" /></label><label>审核金额<input v-model.number="form.approvedAmount" type="number" min="0" /></label><label>已收/付款金额<input v-model.number="form.paidAmount" type="number" min="0" /></label><label>经办人<input v-model.trim="form.manager" /></label><label class="wide">备注<textarea v-model.trim="form.notes" rows="3"></textarea></label></div><footer><button type="button" class="secondary" @click="showForm=false">取消</button><button class="primary" :disabled="saving">{{saving?'保存中…':'保存'}}</button></footer></form></div>
</div></template>
<script>
const money={methods:{fmt(v){return new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format(v||0)}}}
const ContractTable={mixins:[money],props:['items'],emits:['edit','remove'],template:`<div class="table-wrap"><table><thead><tr><th>合同编号</th><th>合同名称 / 相对方</th><th>类型</th><th>合同金额</th><th>已结算</th><th>履约状态</th><th>经办人</th><th></th></tr></thead><tbody><tr v-for="c in items" :key="c.id"><td><code>{{c.number}}</code></td><td><b>{{c.name}}</b><small>{{c.counterparty}}</small></td><td><span :class="['type-pill',c.type]">{{c.type==='owner'?'对业主':'对分包'}}</span></td><td class="money">{{fmt(c.amount)}}</td><td class="money">{{fmt(c.settledAmount)}}</td><td><span class="status"><i></i>{{c.status}}</span></td><td>{{c.manager||'—'}}</td><td class="actions"><button @click="$emit('edit',c)">编辑</button><button @click="$emit('remove',c)">删除</button></td></tr><tr v-if="!items.length"><td colspan="8" class="empty">暂无合同记录</td></tr></tbody></table></div>`}
const SettlementTable={mixins:[money],props:['items'],emits:['edit','remove'],template:`<div class="table-wrap"><table><thead><tr><th>结算编号 / 期间</th><th>合同名称 / 相对方</th><th>申报金额</th><th>审核金额</th><th>已收/付款</th><th>状态</th><th>经办人</th><th></th></tr></thead><tbody><tr v-for="s in items" :key="s.id"><td><code>{{s.number}}</code><small>{{s.period||'未填写期间'}}</small></td><td><b>{{s.contractName}}</b><small>{{s.counterparty}} · {{s.contractNumber||'未关联编号'}}</small></td><td class="money">{{fmt(s.reportedAmount)}}</td><td class="money">{{fmt(s.approvedAmount)}}</td><td class="money">{{fmt(s.paidAmount)}}</td><td><span class="status"><i></i>{{s.status}}</span></td><td>{{s.manager||'—'}}</td><td class="actions"><button @click="$emit('edit',s)">编辑</button><button @click="$emit('remove',s)">删除</button></td></tr><tr v-if="!items.length"><td colspan="8" class="empty">暂无结算记录</td></tr></tbody></table></div>`}
export default{components:{ContractTable,SettlementTable}}
</script>
